name: Publish

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup node
      uses: actions/setup-node@v2-beta
      with:
        node-version: '12'
    - run: sudo apt-get install xvfb
    - run: npm install
    - run: npm run lint
    - run: xvfb-run --auto-servernum npm run test
    - run: npm run compile
    - run: npm install -g vsce
    - run: vsce publish -p ${{ secrets.VSCE_TOKEN }}
      env:
        CI: true
